"""
格式化输出 — BriefItem 列表 → Telegram HTML / 邮件 / Markdown。
"""
from datetime import datetime, timezone
from .summarizer import BriefItem

SENTIMENT_EMOJI = {
    "看涨": "🟢",
    "看跌": "🔴",
    "中性": "⚪",
    "信息": "🔵",
}

CATEGORY_EMOJI = {
    "Crypto": "₿",
    "Tech": "💻",
    "AI": "🤖",
    "投资": "📈",
    "留学": "🎓",
    "新闻": "📰",
    "其他": "📌",
}


def format_telegram_html(items: list[BriefItem], title: str = "📋 AI 每日简报") -> str:
    """格式化为 Telegram HTML 消息"""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"<b>{title}</b>", f"<i>{now}</i>", ""]

    if not items:
        lines.append("今日暂无值得关注的信息。")
        return "\n".join(lines)

    for item in items:
        sentiment_emoji = SENTIMENT_EMOJI.get(item.sentiment, "🔵")
        cat_emoji = CATEGORY_EMOJI.get(item.category, "📌")
        kw_tags = " ".join(f"#{kw}" for kw in item.keywords[:3])

        lines.append(
            f"{sentiment_emoji} <b>{item.title}</b>\n"
            f"{item.summary_cn}\n"
            f"重要度 {'⭐' * item.importance} | {cat_emoji} {item.category} | {kw_tags}\n"
            f'<a href="{item.source_url}">🔗 原文链接</a>'
        )
        lines.append("")

    return "\n".join(lines)


def format_markdown_digest(items: list[BriefItem]) -> str:
    """格式化为 Markdown 日报（存档用）"""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# AI 每日简报 — {now}",
        "",
        "| # | 标题 | 摘要 | 情绪 | 重要度 | 分类 |",
        "|---|------|------|------|--------|------|",
    ]

    for i, item in enumerate(items, 1):
        lines.append(
            f"| {i} | [{item.title}]({item.source_url}) | {item.summary_cn[:60]}... | "
            f"{SENTIMENT_EMOJI.get(item.sentiment, '')} {item.sentiment} | "
            f"{item.importance}/10 | {item.category} |"
        )

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by AI_OS at {now}*")
    return "\n".join(lines)
